### ISSUE TITLE
Proposing to move this repo to the playframework org

### ISSUE THREAD

**Issue by mkurz** [playframework/flyway-play#390]
Hi everyone and @tototoshi,

I am in contact with @alistair-RG from the Flyway team at Redgate. They want to have some tidy-up done this year and this is why we will very likely move this repo to the https://github.com/playframework/ organization.
After the move we will also change the groupid to `org.playframework`.

@tototoshi Even if we move this repo, can you continue to maintain it? I will help to set up GitHub actions workflows for publishing, etc. but is it ok if you stay the main maintainer of this repo?

Thanks!

- Related ticket: https://github.com/flyway/flyway-sbt/issues/93

**Comment by tototoshi** [comment]
> is it ok if you stay the main maintainer of this repo?

OK!

**Comment by mkurz** [comment]
@alistair-RG we have green light :+1:

**Comment by ihostage** [comment]
Hi, folks! I agree it's a very good idea! 👍

**Comment by mkurz** [comment]
I am in contact with Redgate, the repo should be transferred this year hopefully :crossed_fingers:
